// @generated by scripts/generate_product_data.py
// Source files:
// - crates/emwin-parser/data/afos_routing_overrides.json
// Do not edit manually.

#[allow(unused_imports)]
use super::{AfosRoutingOverride, TextProductBodyBehavior, TextProductRouting};
#[allow(unused_imports)]
use crate::body::BodyExtractorId;

#[allow(dead_code)]
pub const AFOS_ROUTING_GENERATED_AT_UTC: &str = "2026-03-16T23:05:58Z";
pub const AFOS_ROUTING_OVERRIDE_COUNT: usize = 10;

pub static AFOS_ROUTING_OVERRIDES: [AfosRoutingOverride; AFOS_ROUTING_OVERRIDE_COUNT] = [
    AfosRoutingOverride {
        afos: "FFGMPD",
        title: Some("Mesoscale precipitation discussion"),
        routing: Some(TextProductRouting::Mcd),
        body_behavior: Some(TextProductBodyBehavior::Never),
        extractors: None,
    },
    AfosRoutingOverride {
        afos: "NBXUSA",
        title: Some("NBM NBX Guidance"),
        routing: Some(TextProductRouting::Mos),
        body_behavior: Some(TextProductBodyBehavior::Never),
        extractors: None,
    },
    AfosRoutingOverride {
        afos: "PFWF38",
        title: Some("Days 3-8 fire weather outlook points"),
        routing: Some(TextProductRouting::SpcOutlook),
        body_behavior: Some(TextProductBodyBehavior::Never),
        extractors: None,
    },
    AfosRoutingOverride {
        afos: "PFWFD1",
        title: Some("Day 1 fire weather outlook points"),
        routing: Some(TextProductRouting::SpcOutlook),
        body_behavior: Some(TextProductBodyBehavior::Never),
        extractors: None,
    },
    AfosRoutingOverride {
        afos: "PFWFD2",
        title: Some("Day 2 fire weather outlook points"),
        routing: Some(TextProductRouting::SpcOutlook),
        body_behavior: Some(TextProductBodyBehavior::Never),
        extractors: None,
    },
    AfosRoutingOverride {
        afos: "PRCUS",
        title: None,
        routing: Some(TextProductRouting::Pirep),
        body_behavior: Some(TextProductBodyBehavior::Never),
        extractors: None,
    },
    AfosRoutingOverride {
        afos: "RBG94E",
        title: Some("Day 1 excessive rainfall outlook"),
        routing: Some(TextProductRouting::Ero),
        body_behavior: Some(TextProductBodyBehavior::Never),
        extractors: None,
    },
    AfosRoutingOverride {
        afos: "RBG98E",
        title: Some("Day 2 excessive rainfall outlook"),
        routing: Some(TextProductRouting::Ero),
        body_behavior: Some(TextProductBodyBehavior::Never),
        extractors: None,
    },
    AfosRoutingOverride {
        afos: "RBG99E",
        title: Some("Day 3 excessive rainfall outlook"),
        routing: Some(TextProductRouting::Ero),
        body_behavior: Some(TextProductBodyBehavior::Never),
        extractors: None,
    },
    AfosRoutingOverride {
        afos: "SWOMCD",
        title: Some("Mesoscale discussion"),
        routing: Some(TextProductRouting::Mcd),
        body_behavior: Some(TextProductBodyBehavior::Never),
        extractors: None,
    },
];
